#!/usr/bin/env python

import sys, string
import alignment

def get_dna(f):
    dna = []
    for line in f:
        blockname = string.strip(line)
        if not blockname[:9] == '<<Object ':
            dna.append(blockname) 
    return dna

def main():
    # Command-line arguments
    f1 = open(sys.argv[1], 'r')
    f2 = open(sys.argv[2], 'r')

    block_dna_1 = get_dna(f1) 
    block_dna_2 = get_dna(f2) 

    alignment.needle(block_dna_1, block_dna_2)

if __name__ == '__main__':
    main()
